name: CI

on:
  push:
    branches: [ help ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install
        run: pnpm i --legacy-peer-deps

      - name: build
        run: pnpm run build

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: help
          folder: dist/public
